In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import random

In [7]:
r = pd.read_csv(r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB")
r

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.0,150.00,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.0,149.00,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2.0,150.00,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2.0,2.0,40.00,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2.0,2.0,83.00,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7115,3.0,2.0,325.00,2900.0,3,11206.896552,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7116,3.0,1.0,84.83,1780.0,3,4765.730337,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7117,2.0,1.0,48.00,880.0,2,5454.545455,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
7118,2.0,1.0,55.00,1000.0,2,5500.000000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7119,2.0,1.0,78.00,1400.0,3,5571.428571,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
X = r.drop("price",axis=1)
X

,bath,balcony,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,location_Whitefield,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.0,1672.0,3,8971.291866,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.0,1750.0,3,8514.285714,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2.0,1750.0,3,8571.428571,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2.0,2.0,1250.0,2,3200.000000,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,2.0,2.0,1200.0,2,6916.666667,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7115,3.0,2.0,2900.0,3,11206.896552,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7116,3.0,1.0,1780.0,3,4765.730337,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7117,2.0,1.0,880.0,2,5454.545455,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
7118,2.0,1.0,1000.0,2,5500.000000,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
7119,2.0,1.0,1400.0,3,5571.428571,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
y = r["price"]
y

0       150.00
1       149.00
2       150.00
3        40.00
4        83.00
         ...
7115    325.00
7116     84.83
7117     48.00
7118     55.00
7119     78.00
Name: price, Length: 7120, dtype: float64

In [10]:
print("shape of X ",X.shape)

shape of X  (7120, 107)

In [11]:
print("shape of Y ",y.shape)

shape of Y  (7120,)

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state = 51)

In [13]:
print("shape of x_train = " , X_test.shape)
print("shape of x_train = " , X_train.shape)

shape of x_train =  (2136, 107)
shape of x_train =  (4984, 107)

In [14]:
from sklearn.preprocessing import StandardScaler
sd = StandardScaler()
print(sd.fit(X_train))

StandardScaler()

In [16]:
X_train

,bath,balcony,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,location_Whitefield,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
2890,3.0,1.0,1832.0,3,6823.144105,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
6777,4.0,3.0,4827.0,4,8286.720530,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
771,2.0,0.0,1350.0,3,6148.148148,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
17,1.0,0.0,440.0,1,6363.636364,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2304,2.0,2.0,1570.0,3,6050.955414,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6672,2.0,1.0,1246.0,2,5457.463884,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1733,2.0,1.0,1010.0,2,5742.574257,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1760,2.0,2.0,1080.0,2,4629.629630,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
485,2.0,2.0,982.0,2,2500.000000,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2105,2.0,1.0,1000.0,2,2888.000000,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
X_train = sd.transform(X_train)
X_train

array([[ 0.71863018, -0.74909794,  0.4607453 , ..., -0.05675044,
        -0.06020505, -0.05494284],
       [ 1.87736613,  1.84770449,  4.25411957, ..., -0.05675044,
        -0.06020505, -0.05494284],
       [-0.44010577, -2.04749915, -0.14974098, ..., -0.05675044,
        -0.06020505, -0.05494284],
       ...,
       [-0.44010577,  0.54930328, -0.49171462, ..., -0.05675044,
        -0.06020505, -0.05494284],
       [-0.44010577,  0.54930328, -0.61583838, ..., -0.05675044,
        -0.06020505, -0.05494284],
       [-0.44010577, -0.74909794, -0.59304014, ..., -0.05675044,
        -0.06020505, -0.05494284]])

In [18]:
X_test = sd.transform(X_test)
X_test

array([[ 0.71863018,  0.00965623,  0.29355819, ..., -0.05675044,
        -0.06020505, -0.05494284],
       [-0.44010577,  0.54930328, -0.57277504, ..., -0.05675044,
        -0.06020505, -0.05494284],
       [ 1.87736613,  0.54930328,  0.61020044, ..., -0.05675044,
        -0.06020505, -0.05494284],
       ...,
       [ 3.03610208, -0.74909794,  1.10416237, ..., -0.05675044,
        -0.06020505, -0.05494284],
       [-0.44010577, -2.04749915, -0.33972633, ..., -0.05675044,
        -0.06020505, -0.05494284],
       [-0.44010577, -2.04749915, -0.33972633, ..., -0.05675044,
        -0.06020505, -0.05494284]])

In [20]:
X_train[0]

array([ 0.71863018, -0.74909794,  0.4607453 ,  0.66079676,  0.36514298,
        0.57240764, -0.47071077, -0.25172755,  0.50945074, -0.18153063,
       -0.16365218, -0.14882642, -0.13250731, -0.13093073, -0.12772319,
        7.98293635, -0.13172122, -0.12526719, -0.11761116, -0.11584511,
       -0.11038666, -0.1094518 , -0.10268101, -0.10660036, -0.09328822,
       -0.08287754, -0.08994785, -0.08994785, -0.08648283, -0.09107446,
       -0.08529752, -0.07911279, -0.08529752, -0.07241581, -0.07781846,
       -0.07781846, -0.0751646 , -0.08164141, -0.0751646 , -0.07380273,
       -0.07241581, -0.07650277, -0.07380273, -0.08164141, -0.07911279,
       -0.08409599, -0.06658601, -0.07650277, -0.07100239, -0.07380273,
       -0.07100239, -0.06956083, -0.0751646 , -0.07100239, -0.06347447,
       -0.06020505, -0.06347447, -0.06347447, -0.06504853, -0.05494284,
       -0.0585029 , -0.06658601, -0.06808937, -0.06186103, -0.06808937,
       -0.06020505, -0.06347447, -0.06658601, -0.06186103, -0.06020505,
       -0.0585029 , -0.0585029 , -0.06186103, -0.05307449, -0.06186103,
       -0.06186103, -0.06186103, -0.06020505, -0.05494284, -0.06186103,
       -0.05494284, -0.06186103, -0.06347447, -0.0585029 , -0.06020505,
       -0.06186103, -0.06186103, -0.0585029 , -0.06186103, -0.06020505,
       -0.06186103, -0.06347447, -0.05307449, -0.05494284, -0.0585029 ,
       -0.05494284, -0.05675044, -0.05494284, -0.04483809, -0.05494284,
       -0.05113871, -0.05307449, -0.05307449, -0.05494284, -0.05675044,
       -0.06020505, -0.05494284])

In [21]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [24]:
lr.coef_

array([-4.88304646e+00, -1.43040097e+00,  8.55126824e+01, -1.60394635e+01,
        5.76820052e+01,  2.28631794e-01, -1.93404594e+00, -4.46518138e+00,
       -2.51317990e+00, -4.47799652e+00, -2.45169738e+00,  5.70356197e-01,
       -1.07211688e+00,  1.56740455e+00,  6.83696669e-03, -1.54678667e+00,
       -5.94765523e-02,  2.32802026e+00, -1.50771440e+00,  1.89638073e+00,
       -3.30384481e+00, -1.30759470e+00, -9.49980604e-01, -1.17854356e-01,
        1.10782891e+00,  1.29968102e+00, -3.55530464e+00, -1.40421033e+00,
       -4.08047349e-01,  1.54728574e+00, -4.16562589e-01, -1.36393616e-01,
        7.78731709e-01, -1.35273506e+00,  3.17112309e-02, -1.52387663e+00,
        4.05394857e-01,  8.47374351e-01,  3.15748162e+00, -7.69005961e-03,
        1.26409325e-01,  2.59385798e-01, -3.73413968e-01,  1.18454294e+00,
       -1.50449224e+00, -3.43095568e+00, -2.74701332e-02, -7.43867003e-02,
       -8.44815634e-01, -1.18983401e+00, -9.42078883e-01,  4.61660052e-01,
        9.69693794e-01, -8.35902250e-01, -1.07509942e+00,  1.14327741e+00,
        2.25483063e+00, -5.20471444e-01, -1.42039137e+00, -7.56244023e-01,
        1.28216694e+00, -1.38004437e-01,  7.69267281e-02, -6.55593797e-02,
       -2.04501399e+00,  1.54591123e+00, -1.00809665e+00, -9.44606814e-01,
       -7.49951669e-01, -1.02819875e-02, -6.44513773e-01, -1.93631628e-01,
       -1.87236358e+00, -1.14476175e+00,  6.03687661e-01,  1.51511937e+00,
       -1.30977917e+00,  3.26905216e-01, -7.13120709e-01, -2.28616137e+00,
        1.76920834e-01, -7.30005030e-03,  1.26967616e-01,  3.03194501e+00,
        2.03143616e+00, -8.09372408e-01, -4.01263577e-01,  2.44878918e+00,
       -9.35212264e-02, -1.79711872e-02,  1.18087291e-02,  1.71900654e+00,
        9.15937836e-01, -1.19222500e+00,  3.63432030e-01, -8.14945721e-01,
        1.71969114e+00,  4.99397309e-01,  8.30774007e-01,  5.23810045e-01,
       -2.92037742e-01, -1.38804651e+00, -7.46194112e-01,  5.95976777e-01,
       -1.84928823e+00,  2.65054034e-01, -3.56413676e-01])

In [26]:
lr.intercept_

95.16795846709468

In [28]:
X_test[0, :]

array([ 0.71863018,  0.00965623,  0.29355819,  0.66079676, -0.48037699,
       -1.74700673,  2.12444683, -0.25172755,  0.50945074, -0.18153063,
       -0.16365218, -0.14882642, -0.13250731, -0.13093073, -0.12772319,
       -0.12526719, -0.13172122, -0.12526719, -0.11761116, -0.11584511,
       -0.11038666, -0.1094518 , -0.10268101, -0.10660036, -0.09328822,
       -0.08287754, -0.08994785, -0.08994785, -0.08648283, -0.09107446,
       -0.08529752, -0.07911279, -0.08529752, -0.07241581, -0.07781846,
       -0.07781846, -0.0751646 , -0.08164141, -0.0751646 , -0.07380273,
       -0.07241581, -0.07650277, -0.07380273, -0.08164141, -0.07911279,
       -0.08409599, -0.06658601, -0.07650277, -0.07100239, -0.07380273,
       -0.07100239, -0.06956083, -0.0751646 , -0.07100239, -0.06347447,
       -0.06020505, -0.06347447, -0.06347447, -0.06504853, -0.05494284,
       -0.0585029 , -0.06658601, -0.06808937, -0.06186103, -0.06808937,
       -0.06020505, -0.06347447, -0.06658601, -0.06186103, -0.06020505,
       -0.0585029 , -0.0585029 , -0.06186103, -0.05307449, -0.06186103,
       -0.06186103, -0.06186103, -0.06020505, -0.05494284, -0.06186103,
       -0.05494284, -0.06186103, -0.06347447, -0.0585029 , -0.06020505,
       -0.06186103, -0.06186103, -0.0585029 , -0.06186103, -0.06020505,
       -0.06186103, -0.06347447, -0.05307449, -0.05494284, -0.0585029 ,
       -0.05494284, -0.05675044, -0.05494284, -0.04483809, -0.05494284,
       -0.05113871, -0.05307449, -0.05307449, -0.05494284, -0.05675044,
       -0.06020505, -0.05494284])

In [29]:
lr.predict([X_test[0, :]])

array([75.87705017])

In [31]:
lr.predict(X_test)

array([ 75.87705017,  12.87613424, 113.79758743, ..., 139.67952741,
        56.1138439 ,  68.28262617])

In [32]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...
5297     53.87
1308     37.20
5411    129.00
4701     67.00
6366     60.00
Name: price, Length: 2136, dtype: float64

In [33]:
lr.score(X_test,y_test)

0.8068382834771934